trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    az bicep build --file $(Build.SourcesDirectory)/newbicep.bicep
  displayName: 'Validate syntax using Azure Bicep CLI'
- script: |
    echo Deploying resources to Azure
    az login 
    az deployment group create --resource-group mohan --template-file newbicep.bicep
  displayName: 'Deploy to Azure'