trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  path: bise.bicep

- script: |
    cd bise.bicep
    echo Validating the syntax...
    az deployment group validate --template-file azure-pipelines.yml 
  displayName: 'Validate syntax'

- script: |
    echo Deploying resources to Azure...
    az deployment group create --template-file azure-pipelines.yml
  displayName: 'Deploy to Azure'
