trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  path: source_code

- script: |
    cd source_code
    echo Validating the syntax...
    az deployment group validate --template-file bise.bicep 
  displayName: 'Validate syntax'

- script: |
    echo Deploying resources to Azure...
    az deployment group create --template-file bise.bicep 
  displayName: 'Deploy to Azure'
